// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {MxObject} sensorReading
 * @returns {Promise.<void>}
 */
export async function JA_StartTimer(sensorReading) {
	// BEGIN USER CODE
    if (!sensorReading) return Promise.resolve();

    // Boa prática: Mata o timer anterior armazenado globalmente se ele já existir
    if (window.industrialDashboardTimer) {
        clearInterval(window.industrialDashboardTimer);
    }

    // Armazena o ID do novo timer na janela global do navegador
    window.industrialDashboardTimer = window.setInterval(() => {
        mx.data.action({
            params: {
               actionname: "MyFirstModule.MF_UpdateDashboard",
                applyto: "selection",
                guids: [sensorReading.getGuid()]
            },
            error: function(error) {
                console.error("Erro no loop de atualização: ", error);
            }
        });
    }, 30000);

    return Promise.resolve();
	// END USER CODE
}
